// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace BlazorDKJ.Models
{
    public partial class mczeContext : DbContext
    {
        public mczeContext()
        {
        }

        public mczeContext(DbContextOptions<mczeContext> options)
            : base(options)
        {
        }

        public virtual DbSet<tbjm> tbjm { get; set; }
        public virtual DbSet<tbtowar> tbtowar { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<tbjm>(entity =>
            {
                entity.HasKey(e => e.IDJm)
                    .HasName("PK_tbjm_IDJm");

                entity.ToTable("tbjm", "mcze");

                entity.Property(e => e.Jm).HasMaxLength(5);

                entity.Property(e => e.Opis).HasMaxLength(25);
            });

            modelBuilder.Entity<tbtowar>(entity =>
            {
                entity.HasKey(e => e.IDTowar)
                    .HasName("PK_tbtowar_IDTowar");

                entity.ToTable("tbtowar", "mcze");

                entity.HasIndex(e => e.FGrupa, "FGrupa_idx");

                entity.HasIndex(e => e.FJm, "FJm_idx");

                entity.Property(e => e.Ean).HasMaxLength(45);

                entity.Property(e => e.Indeks).HasMaxLength(45);

                entity.Property(e => e.Nazwa).HasMaxLength(65);

                entity.Property(e => e.Opis).HasMaxLength(45);

                entity.HasOne(d => d.FJmNavigation)
                    .WithMany(p => p.tbtowar)
                    .HasForeignKey(d => d.FJm)
                    .OnDelete(DeleteBehavior.Cascade)
                    .HasConstraintName("tbtowar$FJm");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}