// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BlazorDKJ.Models
{
    public partial class tbjm
    {
        public tbjm()
        {
            tbtowar = new HashSet<tbtowar>();
        }

        public int IDJm { get; set; }
        public string Jm { get; set; }
        public string Opis { get; set; }

        public virtual ICollection<tbtowar> tbtowar { get; set; }
    }
}