// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BlazorDKJ.Models
{
    public partial class tbtowar
    {
        public int IDTowar { get; set; }
        public string Nazwa { get; set; }
        public string Indeks { get; set; }
        public string Ean { get; set; }
        public int? FJm { get; set; }
        public int? Pozycja { get; set; }
        public int? FGrupa { get; set; }
        public string Opis { get; set; }
        public int? Ilosciowa { get; set; }

        public virtual tbjm FJmNavigation { get; set; }
    }
}